# Generated by Django 3.1.1 on 2020-09-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_auto_20200904_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.DateField(),
        ),
    ]
